#!/usr/bin/env bash

if [ $# -gt 0 ]; then

    if [ "$1" == "test" ]; then
        shift 1
        COMMAND="./vendor/bin/pest $@ --parallel"

    elif [ "$1" == "coverage" ]; then
        shift 1
        COMMAND="./vendor/bin/pest $@ --coverage --parallel"

    elif [ "$1" == "serve" ]; then
        shift 1
        docker run -it --rm \
            -u $(id -u):$(id -g) \
            -p 8000:8000 \
            -v $PWD:/app \
            -w /app \
            tombenevides/xdebug-php:v8.1 php -S 0.0.0.0:8000 public/index.php

        exit 0

    else
        COMMAND="$@"
    fi
else
    COMMAND="ls"

fi

docker run -it --rm \
    -u $(id -u):$(id -g) \
    -v $PWD:/app \
    -w /app \
    tombenevides/xdebug-php:v8.1 $COMMAND